package config

type License struct {
	DeviceID     string `json:"device_id"`
	Mac          string `json:"mac"`
	Type         string `json:"type"`
	Store        string `json:"store"`
	End          int64  `json:"end"`
	Start        int64  `json:"start"`
	CounterLimit int    `json:"limit_counter"`
	ScreenLimit  int    `json:"limit_screen"`
	KioskLimit   int    `json:"limit_kiosk"`
}

// a base32 encoded private key generated by `lkgen gen`
// note that you might prefer reading it from a file...
const privateKeyStr = "KP+BAwEBC3BrQ29udGFpbmVyAf+CAAECAQNQdWIBCgABAUQB/4QAAAAK/4MFAQL/hgAAAP+Z/4IBYQQFGJh9YXqf3eC0wqMe/ZnxzIo3Egt+OeIIxUxBMc/vJjvkxTBLnqNYgvJopWKFqQK19FW6xsAj4ivfYXO4BwLGaLld3UBu4FYriTfDzQaDtuaMkfHDCti30JFY9Q6vRjYBMQJHV0DUdY/dt8Xef6tdb8CO0kfbgNYYJDeBimg+bi+33ePeycGnv8KQb4qQmsHw1CkA"
const publicKeyStr = "BAUYmH1hep/d4LTCox79mfHMijcSC3454gjFTEExz+8mO+TFMEueo1iC8milYoWpArX0VbrGwCPiK99hc7gHAsZouV3dQG7gViuJN8PNBoO25oyR8cMK2LfQkVj1Dq9GNg=="

const (
	LICENSE_NEW  = "NEW"
	LICENSE_USED = "USED"
)
