package config

type License struct {
	DeviceID     string `json:"device_id"`
	Mac          string `json:"mac"`
	Type         string `json:"type"`
	Store        string `json:"store"`
	End          int64  `json:"end"`
	Start        int64  `json:"start"`
	CounterLimit int    `json:"limit_counter"`
	ScreenLimit  int    `json:"limit_screen"`
	KioskLimit   int    `json:"limit_kiosk"`
}

// a base32 encoded private key generated by `lkgen gen`
// note that you might prefer reading it from a file...
const privateKeyStr = "KP+BAwEBC3BrQ29udGFpbmVyAf+CAAECAQNQdWIBCgABAUQB/4QAAAAK/4MFAQL/hgAAAP+Z/4IBYQTnJf9nFeN5FdBHqKuqtioLJc6x8919FRXt8TFzJBtoCzbHHANJ1OzDezp53aQZGjMbfdDO+xml7BJtkcipSQInTpGwdkUM71gaUtKV/L+8v63i3tKj/6r2J53fqhDR+5IBMQLTigK39HS526gVT928wt6EDa5a/CdY1/DPCA1LRU2iClqerPrXESinoGVR/Bl5socA"
const publicKeyStr = "BOcl/2cV43kV0Eeoq6q2KgslzrHz3X0VFe3xMXMkG2gLNsccA0nU7MN7OnndpBkaMxt90M77GaXsEm2RyKlJAidOkbB2RQzvWBpS0pX8v7y/reLe0qP/qvYnnd+qENH7kg=="

const (
	LICENSE_NEW  = "NEW"
	LICENSE_USED = "USED"
)
